### ISSUE TITLE
Add possibility to specify a custom css file in the preferences

### ISSUE THREAD

**Issue by felipevicencion** [DD2480-Group-22/jabref#1]
A simple way to specify a custom css file is needed, so an option should be added to the preference dialog.

**Comment by nilsstre** [comment]
See original issue: https://github.com/JabRef/jabref/issues/5790

**Comment by nilsstre** [comment]
- [x] Button and dialogue for importing CSS in preferences

- [x] Add translation for button text, tooltip and error dialogue

- [x] Save path to the imported CSS file (in jabref.xml?)

- [x] Button for toggling between standard and custom CSS
